### ISSUE TITLE
[get-graphql-schema] The characters after the ‘=’ in the header value are cut off

### ISSUE THREAD

**Issue by kosyacore** [DanteUkraine/playwright-graphql#15]
Hey there, firstly I want to thank you for developing this project!

**Describe the bug**
If there is an "‘=’" sign in the header value, everything after it is trimmed. I can't get a GraphQL schema as my project uses a `Cookie` header with the `sid=<value>` for authorisation.

Example:
`get-graphql-schema https://url.test/graphql -h "Cookie=sid=<value>"`

Result:
`Cookie: "sid"`

This is a known issue in this dependency and has been fixed, but the version with the fix has not been published in the npm registry.

Issue: https://github.com/prisma-labs/get-graphql-schema/issues/27
Fix: https://github.com/prisma-labs/get-graphql-schema/commit/8ae5795b9ea7ad505a10da718eec7972ae4a98a4

I've been looking for a replacement for this dependency, but there is no lightweight alternative, and I don't want to add a heavy dependency like `graphql-cli` or `apollo` to the project just to get the schema.

This tool looks like a lightweight alternative, but I haven't had a chance to test it yet: https://github.com/jkmartindale/gql-sdl

**Comment by DanteUkraine** [comment]
Hey @kosyacore, interesting issue, I investigated a source of issue, with is another sub-dependency used to parse query to object: https://github.com/unshiftio/querystringify/blob/60d8dd92aeb5550fb79b93e6dae193d02e029daf/index.js#L43
Looks like this method parses only first level of values.

But I have good news for you since I figured out working query: `"Cookie={"sid": "value"}"` second part of key=value should be plain json.
`get-graphql-schema https://url.test/graphql -h "Cookie={"sid": "value"}"`

Tested on my local graphql server:
<img width="605" alt="Screenshot 2024-12-28 at 18 21 57" src="https://github.com/user-attachments/assets/fd3613fb-a73f-443b-9206-bb728e1c7e68" />

**Comment by DanteUkraine** [comment]
Not a bug.
